### ISSUE TITLE
Create Poc tests for backstage application

### ISSUE THREAD

**Issue by josephca** [janus-idp/showcase-e2e#1]
## Goal
Create initial PoC tests for Backstage application

## What problem does this solve? Please describe.
Backstage developers want to be able to test Backstage applications with their components

## Use cases
As a backstage developer, I should be able to run some integration tests.

## Acceptance criteria
- [x] Evaluate cypress test framework for Backstage
- [x] Evaluate [frontside interactor to use with cypress](https://frontside.com/blog/2022-03-03-backstage-tutorial-plugin-tests-interactors/)
- [x] Create a simple happy path tests with Github action
   - [x] install Backstage helm chart on Minikube and run tests 
   - [x] install Janus-IDP helm chart on OpenShift and run tests

## Issues in Epic
- [ ] tbd
