### ISSUE TITLE
Create and setup automated tests for Showcase

### ISSUE THREAD

**Issue by josephca** [janus-idp/showcase-e2e#2]
## Goal
Create and setup test infrastructure to run automated tests on Backstage Showcase

## What problem does this solve? Please describe.
Automate tests to run by a schedule or upon demand (e.g. PRs, code updates) to ensure the quality of the Showcase image

## Acceptance criteria
- [x] Setup Github action to run tests by using Showcase helm chart
   - [x] Update tests to use updated showcase helm chart
     - [x] Depends on [Updates to Helm chart](https://github.com/janus-idp/book/issues/14) 
   - [x] Setup Github action tests with OpenShift and k8s. 
- [x] Setup ToolChain/pipeline tests with OpenShift and k8s that can be kicked off by PRs and branch updates

**Comment by josephca** [comment]
Updated to use the refreshed showcase helm chart : https://github.com/janus-idp/showcase-e2e/pull/19
